### ISSUE TITLE
Unable to compile the C++ example on Ubuntu 22.04 and g++ 11.4.0

### ISSUE THREAD

**Issue by vanem** [QuantumLeaps/State-Oriented-Programming#1]
The error message is:
```
 g++ watch.cpp hsm.cpp -o watch
watch.cpp: In constructor ‘Watch::Watch()’:
watch.cpp:209:28: error: cannot convert ‘Watch::topHndlr’ from type ‘const Msg* (Watch::)(const Msg*)’ to type ‘EvtHndlr’ {aka ‘const Msg* (Hsm::*)(const Msg*)’}
  209 |   : Hsm("Watch", (EvtHndlr)topHndlr),
      |                            ^~~~~~~~
hsm.cpp: In member function ‘void Hsm::onStart()’:
```

The C examples compiles & works just fine

This HSM implementation is still relevant and beautiful in its simplicity (and not just for embedded) . My C++ is very basic, how can the code be fixed to work on modern g++?

**Comment by quantum-leaps** [comment]
Thanks for your interest in this older article (from 2000!).
I've updated the code to compile with options "-pedantic -Wall -Wextra".
Please check if this compiles with your g++ 11.
--MMS

**Comment by vanem** [comment]
Thank you for responding!! I was aware that this is based on such an old article, and I know about QP, but this is such a great and simple pattern for what it's able to achieve (and with no other external dependencies). I already used in C and Python (and not only in embedded).
Regarding your code changes, g++ still gives an error message:
```
watch.cpp:211:41: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&Watch::topHndlr’ [-fpermissive]
  211 |   : Hsm("Watch", static_cast<EvtHndlr>(&topHndlr)),
      |                                         ^~~~~~~~
```
but at least the message is meaningful, and the suggested change solves the problem, no more errors/warnings with casts like this:
```
  : Hsm("Watch", static_cast<EvtHndlr>(&Watch::topHndlr)),
```

There are also complains for the use of `register`, but that's obvious.

PS: I apologize, I somehow missed the paragraph in this project readme [Notes About C++ Implementation](https://github.com/QuantumLeaps/State-Oriented-Programming#notes-about-c-implementation), where the cast `reinterpret_cast<EvtHndlr>(&<class>::<func>)` is suggested for newer non-embedded compilers

**Comment by quantum-leaps** [comment]
I've changed the casts in the C++ example code (watch.cpp and hsmtst.cpp) to use `reinterpret_cast<EvtHndlr>(...)`. I hope this will compile and run.
--MMS

**Comment by vanem** [comment]
It does work for me on Ubuntu/x86/gcc11.4.0 c++ standard >=11, by using casts in the form:
`reinterpret_cast<EvtHndlr>(&<class>::<func>))` or `static_cast<EvtHndlr>(&<class>::<func>))`
for example:
` static_cast<EvtHndlr>(&Watch::timekeepingHndlr)` or ` reinterpret_cast<EvtHndlr>(&Watch::timekeepingHndlr)`
Having the fully qualified methodname `<class>::<func>` is required for an error free build
I closed the issue, thank you!

**Comment by quantum-leaps** [comment]
OK, I fixed the issues noted for posteriority.
